apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-transcoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-transcoder
  template:
    metadata:
      labels:
        app: video-transcoder
    spec:
      containers:
        - name: video-transcoder-demo
          image: video-transcoder2:latest  # Uses Minikube's Docker env
          imagePullPolicy: Never          # Avoids pulling from registry
          envFrom:
            - configMapRef:
                name: video-transcoder-env
