apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamtube-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50g"
spec:
  ingressClassName: nginx
  rules:
    - host: app.streamtube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamtube-app
                port:
                  number: 8001

    - host: minio.streamtube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000

    - host: minio-console.streamtube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001

    - host: rabbitmq-console.streamtube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672 